jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - continue-on-error: true
      run: yarn install --frozen-lockfile
    - continue-on-error: true
      run: yarn test
name: Build and Tests
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
